---
title: Dataa Types
author: ''
date: '2022-02-21'
slug: dataa-types
categories: []
tags: []
---

## Cat Lovers
```{r}
library(tidyverse)
catlovers <- "https://raw.githubusercontent.com/dearbharat/tidyverse/main/cat-lovers.csv"

cat_lovers <- read_csv(catlovers)
```

### Summarise Cat Lovers Data Set
```{r}
glimpse(cat_lovers)
cat_lovers %>%
  summarise(mean_cats = mean(number_of_cats, na.rm = TRUE))
```
### Fixing the bad data in the numeric column

```{r}
cat_lovers %>%
  mutate(number_of_cats = case_when(
    name == "Ginger Clark" ~ 2,
    name == "Doug Bass"    ~ 3,
    TRUE                   ~ as.numeric(number_of_cats)
    )) %>%
  summarise(mean_cats = mean(number_of_cats))
```
### Numeric Data Summarization

```{r}
cat_lovers %>%
  mutate(
    number_of_cats = case_when(
      name == "Ginger Clark" ~ "2",
      name == "Doug Bass"    ~ "3",
      TRUE                   ~ number_of_cats
      ),
    number_of_cats = as.numeric(number_of_cats)
    ) %>%
  summarise(mean_cats = mean(number_of_cats))
```
## Data Types - Coercion

```{r}

typeof(TRUE)
typeof("hello")
```

## Explicit Coercion

Number Vs Character

```{r}
x <- 1:3
typeof(x)
typeof(as.character(x))
```

Number Vs Logical
```{r}
x <- c(TRUE, FALSE)
typeof(x)
typeof(as.numeric(x))
```

